# This is a basic workflow to help you get started with Actions

name: Get patch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  watch:
    types: [started]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gitpatch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: SET config
        run: |
          echo "KERNEL_SOURCE=$(cat config.env | grep "KERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "KERNEL_SOURCE_BRANCH=$(cat config.env | grep "KERNEL_SOURCE_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "START_COMMIT=$(cat config.env | grep "START_COMMIT" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV

      # Runs a single command using the runners shell
      - name: Update and Upgrade system
        run: |
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
          sudo sed -i 's/azure.archive.ubuntu.com/mirrors.ustc.edu.cn/' /etc/apt/sources.list
          sudo sed -i 's/http:/https:/' /etc/apt/sources.list
          sudo apt update
          sudo apt install git zip

      # Runs a set of commands using the runners shell
      - name: Git kernel linux 4.19-y
        run: |
          git clone ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }}
          mkdir patch
          cd linux
          git format-patch ${{ env.START_COMMIT }}
          cp *.patch ../patch/
          cd ..
          
      - name: zip Patch-${{ env.BUILD_TIME }}
        run: |
          cd $GITHUB_WORKSPACE/patch/
          zip -q -r Patch-${{ env.BUILD_TIME }}.zip *
          cd ..
          ls
      
      - name: Create Release Action
        # You may pin to the exact commit or the version.
        # uses: aaronbarnaby/create-release-action@fcfdd971c588363dcc85f199c7dd21290d7dd985
        uses: aaronbarnaby/create-release-action@v1.0.0
        with:
          # GitHub secret token
          api_token: ${{ secrets.GITHUB_TOKEN }}
          # Git Tag (for auto releases)
          release_tag: Patch-${{ env.BUILD_TIME }}
          # Instead of comparing to provided release_tag it will search for latest tagged release to compare too
          compare_last_tagged_release: true
          # Should this release be marked as a pre-release?
          prerelease: false
          # Release title (for auto releases)
          title: Patch-${{ env.BUILD_TIME }}
          # Assets to upload to the release
          files: patch/Patch-${{ env.BUILD_TIME }}.zip
          
      - name: Upload Patch
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Patch-${{ env.BUILD_TIME }}
          path: patch/Patch-${{ env.BUILD_TIME }}.zip
